name: PullRequest

on:
  push:
    branches: [ master ]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
        ports:
          - 5432:5432

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: SetupJDK
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Maven Build
        run: mvn clean package -D maven.test.skip=true
      - name: Execute Integration tests
        run: mvn verify -P integration-tests -D POSTGRES_USERNAME=${{ secrets.POSTGRES_USERNAME }} -D POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}
